routes/web.php
<?php

use App\Http\Controllers\detailInvoiceController;
use App\Http\Controllers\halamanController;
use App\Http\Controllers\invoiceController;
use App\Http\Controllers\manajemenMemberController;
use App\Http\Controllers\manajemenStokController;
use App\Http\Controllers\sessionController;
use App\Http\Controllers\toDoListController;
use App\Http\Controllers\history;
use App\Models\detailInvoice;
use App\Models\manajemen_member;
use App\Models\manajemenStok;
use Illuminate\Support\Facades\Route;
use Symfony\Component\Routing\Router;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::get('/', [sessionController::class, 'index']);
Route::post('/login', [sessionController::class, 'login']);

Route::middleware(['auth'])->group(function () {
    Route::resource('/manajemen-produk', manajemenStokController::class);
    Route::resource('/manajemen-customer', manajemenMemberController::class);
    Route::resource('/welcome', toDoListController::class);
    Route::resource('/invoice-details', detailInvoiceController::class);
    Route::get('/invoice-details/create/{id}', [detailInvoiceController::class, 'create'])->name('invoice-details.create');
    Route::get('/invoice', [halamanController::class, 'invoice']);
    Route::get('/invoice/print/printInvoice/{id}', [InvoiceController::class, 'printInvoice'])->name('invoice.print.printInvoice');
    Route::get('/invoice/print/printSuratJalan/{id}', [InvoiceController::class, 'printSuratJalan'])->name('invoice.print.printSuratJalan');
    Route::resource('/invoiceMember', invoiceController::class);
    Route::get('/invoiceMember/create/{id}', [invoiceController::class, 'create'])->name('invoiceMember.create');
    Route::get('/rekap', [halamanController::class, 'rekap']);
    Route::get('/rekapBulanan', [halamanController::class, 'rekapBulanan']);
    Route::get('/rekapTahunan', [halamanController::class, 'rekapTahunan']);
    Route::get('/rekapMember', [halamanController::class, 'rekapMember']);
    Route::get('/rekap/print/printRekapBulanan/{bulanTahun}', [halamanController::class, 'printRekapBulanan'])->name('rekap.print.printRekapBulanan');
    Route::get('/rekap/print/printRekapTahunan/{tahun}', [halamanController::class, 'printRekapTahunan'])->name('rekap.print.printRekapTahunan');
    Route::get('/rekap/print/printRekapMember/{id}', [halamanController::class, 'printRekapMember'])->name('rekap.print.printRekapMember');
    Route::get('/about', [halamanController::class, 'about']);
    Route::get('/logout', [sessionController::class, 'logout']);
    Route::get('/manajemen-stok', function () {
        return view('manajemen_stok.index');
    });
    // Route::get('/input-stok', function(){
    //     return view('manajemen_stok.input');
    // });
    Route::get('input-stok', [manajemenStokController::class, 'toFormInput']);
    Route::get('history', [manajemenStokController::class, 'toHistory']);
    Route::resource('/stok', history::class);
});

app/Models/manajemenStok.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class manajemenStok extends Model
{
    use HasFactory;
    protected $table = 'manajemen_stoks';
    protected $guarded = ['id'];
}

app/Http/Controllers/manajemenStokController.php
<?php

namespace App\Http\Controllers;

use App\Models\historyProduk;
use App\Models\manajemenStok;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class manajemenStokController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        return view('manajemen_produk.index')->with([
            'manajemenStok' => manajemenStok::all()
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'namaProduk' => 'required',
            'kemasan' => 'required',
            'jumlahStok' => 'required',
            'satuan' => 'required',
        ]);

        $produk = new manajemenStok;
        $produk->namaProduk = $request->namaProduk;
        $produk->kemasan = $request->kemasan;
        $produk->jumlahStok = $request->jumlahStok;
        $produk->satuan = $request->satuan;

        $produk->save();
        return redirect('manajemen-produk')->with('success', 'berhasil');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'namaProduk' => 'required',
            'kemasan' => 'required',
            'satuan' => 'required',
        ]);

        $produk = manajemenStok::find($id);
        $produk->namaProduk = $request->namaProduk;
        $produk->kemasan = $request->kemasan;
        $produk->satuan = $request->satuan;

        $produk->save();
        return redirect('manajemen-produk')->with('update', 'berhasil');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $produk = manajemenStok::find($id);
        $produk->delete();

        return redirect('manajemen-produk')->with('hapus', 'berhasil');
    }

    public function toFormInput()
    {
        $history = DB::table('history_produks')
            ->join('manajemen_stoks', 'history_produks.idProduk', '=', 'manajemen_stoks.id')
            ->select(
                'history_produks.id',
                'history_produks.tanggal',
                'history_produks.idProduk',
                'history_produks.jumlahMasuk',
                'manajemen_stoks.namaProduk',
                'manajemen_stoks.kemasan',
                'manajemen_stoks.satuan'
            )
            ->orderBy('history_produks.created_at', 'DESC')
            ->limit(5)
            ->get();

        return view('manajemen_stok.input')->with([
            'produks' => manajemenStok::all(),
            'historys' => $history
        ]);
    }
    public function toHistory()
    {
        $history = DB::table('history_produks')
            ->join('manajemen_stoks', 'history_produks.idProduk', '=', 'manajemen_stoks.id')
            ->select(
                'history_produks.id',
                'history_produks.tanggal',
                'history_produks.idProduk',
                'history_produks.jumlahMasuk',
                'manajemen_stoks.namaProduk',
                'manajemen_stoks.kemasan',
                'manajemen_stoks.satuan'
            )
            ->orderBy('history_produks.created_at', 'DESC')
            ->get();

        return view('manajemen_stok.history')->with([
            'historys' => $history
        ]);
    }
}

resources/views/manajemen_stok/history.blade.php
@extends('layout/layout')

@section('title')
    Riwayat - SBK-Web
@endsection

@section('sidebar')
    <!-- Sidebar Start -->
    <div class="sidebar pe-4 pb-3">
        <nav class="navbar bg-secondary navbar-dark">
            <a href="/welcome" class="navbar-brand mx-4 mb-3">
                <h3 class="text-primary"><img src="{{ asset('img/logo2.png') }}" alt=""
                        style="height: 45px; width: 45px;">&nbsp CV. SBK</h3>
            </a>
            <div class="d-flex align-items-center ms-4 mb-4">
                <div class="position-relative">
                    <img class="rounded-circle" src="{{ asset('img/person.png') }}" alt=""
                        style="width: 40px; height: 40px;">
                    <div
                        class="bg-success rounded-circle border border-2 border-white position-absolute end-0 bottom-0 p-1">
                    </div>
                </div>
                <div class="ms-3">
                    <h6 class="mb-0">{{ session('name') }}</h6>
                    <span>Admin</span>
                </div>
            </div>
            <div class="navbar-nav w-100">
                <a href="/welcome" class="nav-item nav-link"><i class="fa fa-tachometer-alt me-2"></i>Home</a>
                <a href="/manajemen-produk" class="nav-item nav-link" style="font-size: 14px;"><i class="fa fa-th me-2"></i>Manajemen Produk</a>
                <a href="/manajemen-stok" class="nav-item nav-link active"><i class="fa fa-cubes me-2"></i>Manajemen Stok</a>
                <a href="/manajemen-customer" class="nav-item nav-link"><i class="fa fa-user me-2"></i>Membership</a>
                <a href="/invoice" class="nav-item nav-link"><i class="fa fa-keyboard me-2"></i>Pesanan</a>
                <a href="/rekap" class="nav-item nav-link"><i class="fa fa-chart-bar me-2"></i>Rekap</a>
            </div>
        </nav>
    </div>
    <!-- Sidebar End -->
@endsection


@section('konten')
    <div class="container-fluid position-relative d-flex p-0">
        <!-- Spinner Start -->
        <div id="spinner"
            class="show bg-dark position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
            <div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">
                <span class="sr-only">Loading...</span>
            </div>
        </div>
        <!-- Spinner End -->


        <!-- Sidebar Start -->

        <!-- Sidebar End -->


        <!-- Content Start -->
        <div class="content">
            <!-- Navbar Start -->
            <nav class="navbar navbar-expand bg-secondary navbar-dark sticky-top px-4 py-0">
                <a href="welcome" class="navbar-brand d-flex d-lg-none me-4">
                    <h2 class="text-primary mb-0"><img src="{{ asset('img/logo2.png') }}" alt=""
                            style="height: 45px; width: 45px;"></h2>
                </a>
                <a href="#" class="sidebar-toggler flex-shrink-0">
                    <i class="fa fa-bars"></i>
                </a>
                <div class="navbar-nav align-items-center ms-auto">
                    <div class="nav-item dropdown">

                    </div>
                    <div class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">
                            <img class="rounded-circle me-lg-2" src="{{ asset('img/person.png') }}" alt=""
                                style="width: 40px; height: 40px;">
                            <span class="d-none d-lg-inline-flex">{{ session('name') }}</span>
                        </a>
                        <div class="dropdown-menu dropdown-menu-end bg-secondary border-0 rounded-0 rounded-bottom m-0">
                            <a href="/logout" class="dropdown-item">Log Out</a>
                        </div>
                    </div>
                </div>
            </nav>
            <!-- Navbar End -->


            <!-- Recent Sales Start -->
            <div class="container-fluid pt-4 px-4">
                <div class="bg-secondary text-center rounded p-4">
                    <h1 class="display-6 mb-0">HISTORY BARANG MASUK</h1>
                </div>
            </div>
            <!-- Recent Sales End -->


            <!-- Widgets Start -->
            <!-- Widgets Start -->
            <div class="container-fluid pt-4 px-4">
                <div class="row g-4">
                    <div class="col-12">
                        <div class="bg-secondary rounded h-100 p-4">
                            <div class="table-responsive">
                                <table class="table" id="tbl_produk">
                                    <thead>
                                        <tr>
                                            <th scope="col">#</th>
                                            <th scope="col">Nama Produk</th>
                                            <th scope="col">Kemasan</th>
                                            <th scope="col">Jumlah Masuk</th>
                                            <th scope="col">Tanggal Masuk</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach ($historys as $no => $item)
                                            <tr>
                                                <th scope="row">{{ $no + 1 }}</th>
                                                <td>{{ $item->namaProduk }}</td>
                                                <td>{{ $item->kemasan }}</td>
                                                <td>{{ $item->jumlahMasuk." ".$item->satuan }}</td>
                                                <td>{{ $item->tanggal }}</td>
                                            </tr>
                                        @endforeach
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Widgets End -->
            <!-- Widgets End -->


            <!-- Footer Start -->
            <div class="container-fluid pt-4 px-4">
                <div class="bg-secondary rounded-top p-4">
                    <div class="row">
                        <div class="col-12 col-sm-6 text-center text-sm-start">
                            &copy; <a href="#">Your Site Name</a>, All Right Reserved.
                        </div>
                        <div class="col-12 col-sm-6 text-center text-sm-end">
                            <!--/*** This template is free as long as you keep the footer author’s credit link/attribution link/backlink. If you'd like to use the template without the footer author’s credit link/attribution link/backlink, you can purchase the Credit Removal License from "https://htmlcodex.com/credit-removal". Thank you for your support. ***/-->
                            Designed By <a href="https://htmlcodex.com">HTML Codex</a>
                            <br>Distributed By: <a href="https://themewagon.com" target="_blank">ThemeWagon</a>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Footer End -->
        </div>
        <!-- Content End -->


        <!-- Back to Top -->
        <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>
    </div>
@endsection

resources/views/manajemen_stok/input.blade.php
@extends('layout/layout')

@section('title')
    Input Stok Produk - SBK-Web
@endsection

@section('sidebar')
    <!-- Sidebar Start -->
    <div class="sidebar pe-4 pb-3">
        <nav class="navbar bg-secondary navbar-dark">
            <a href="/welcome" class="navbar-brand mx-4 mb-3">
                <h3 class="text-primary"><img src="{{ asset('img/logo2.png') }}" alt=""
                        style="height: 45px; width: 45px;">&nbsp CV. SBK</h3>
            </a>
            <div class="d-flex align-items-center ms-4 mb-4">
                <div class="position-relative">
                    <img class="rounded-circle" src="{{ asset('img/person.png') }}" alt=""
                        style="width: 40px; height: 40px;">
                    <div
                        class="bg-success rounded-circle border border-2 border-white position-absolute end-0 bottom-0 p-1">
                    </div>
                </div>
                <div class="ms-3">
                    <h6 class="mb-0">{{ session('name') }}</h6>
                    <span>Admin</span>
                </div>
            </div>
            <div class="navbar-nav w-100">
                <a href="/welcome" class="nav-item nav-link"><i class="fa fa-tachometer-alt me-2"></i>Home</a>
                <a href="/manajemen-produk" class="nav-item nav-link" style="font-size: 14px;"><i
                        class="fa fa-th me-2"></i>Manajemen Produk</a>
                <a href="/manajemen-stok" class="nav-item nav-link active"><i class="fa fa-cubes me-2"></i>Manajemen
                    Stok</a>
                <a href="/manajemen-customer" class="nav-item nav-link"><i class="fa fa-user me-2"></i>Membership</a>
                <a href="/invoice" class="nav-item nav-link"><i class="fa fa-keyboard me-2"></i>Pesanan</a>
                <a href="/rekap" class="nav-item nav-link"><i class="fa fa-chart-bar me-2"></i>Rekap</a>
            </div>
        </nav>
    </div>
    <!-- Sidebar End -->
@endsection


@section('konten')
    <div class="container-fluid position-relative d-flex p-0">
        <!-- Spinner Start -->
        <div id="spinner"
            class="show bg-dark position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
            <div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">
                <span class="sr-only">Loading...</span>
            </div>
        </div>
        <!-- Spinner End -->


        <!-- Sidebar Start -->

        <!-- Sidebar End -->


        <!-- Content Start -->
        <div class="content">
            <!-- Navbar Start -->
            <nav class="navbar navbar-expand bg-secondary navbar-dark sticky-top px-4 py-0">
                <a href="welcome" class="navbar-brand d-flex d-lg-none me-4">
                    <h2 class="text-primary mb-0"><img src="{{ asset('img/logo2.png') }}" alt=""
                            style="height: 45px; width: 45px;"></h2>
                </a>
                <a href="#" class="sidebar-toggler flex-shrink-0">
                    <i class="fa fa-bars"></i>
                </a>
                <div class="navbar-nav align-items-center ms-auto">
                    <div class="nav-item dropdown">

                    </div>
                    <div class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">
                            <img class="rounded-circle me-lg-2" src="{{ asset('img/person.png') }}" alt=""
                                style="width: 40px; height: 40px;">
                            <span class="d-none d-lg-inline-flex">{{ session('name') }}</span>
                        </a>
                        <div class="dropdown-menu dropdown-menu-end bg-secondary border-0 rounded-0 rounded-bottom m-0">
                            <a href="/logout" class="dropdown-item">Log Out</a>
                        </div>
                    </div>
                </div>
            </nav>
            <!-- Navbar End -->


            <!-- Recent Sales Start -->
            <div class="container-fluid pt-4 px-4">
                <div class="bg-secondary text-center rounded p-4">
                    <h1 class="display-6 mb-0">INPUT PRODUK YANG MASUK GUDANG</h1>
                </div>
            </div>
            <!-- Recent Sales End -->


            <!-- Widgets Start -->
            <div class="container-fluid pt-4 px-4">
                <div class="row g-4">
                    <div class="col-sm-12 col-xl-6">
                        <div class="bg-secondary rounded h-100 p-4">
                            <h6 class="mb-4">Form Input Barang Masuk</h6>
                            <form action="{{ route('stok.store') }}" method="post">
                                @csrf
                                <div class="form-floating mb-3">
                                    <select class="form-select" id="floatingSelect"
                                        aria-label="Floating label select example" name="idProduk">
                                        <option selected disabled>Open this select menu</option>
                                        @foreach ($produks as $produk)
                                            <option value="{{ $produk->id }}">
                                                {{ $produk->namaProduk }}&nbsp{{ $produk->kemasan }}
                                            </option>
                                        @endforeach
                                    </select>
                                    <label for="floatingSelect">Silahkan Pilih Produk</label>
                                </div>
                                <div class="form-floating mb-3">
                                    <input type="number" class="form-control" id="floatingPassword" name="jumlahMasuk">
                                    <label for="floatingPassword">Jumlah Produk Masuk</label>
                                </div>
                                <button type="submit" class="btn btn-primary">SIMPAN</button>
                            </form>
                        </div>
                    </div>
                    <div class="col-sm-12 col-xl-6">
                        <div class="bg-secondary rounded h-100 p-4">
                            <div class="d-flex align-items-center justify-content-between mb-4">
                                <h6 class="mb-0">History Terakhir Barang Masuk</h6>
                                <a href="/history" class="btn btn-link m-2 btn-sm">Show All</a>
                            </div>
                            <table class="table table-hover">
                                <thead>
                                    <tr>
                                        <th scope="col">#</th>
                                        <th scope="col">Nama Produk</th>
                                        <th scope="col">Kemasan</th>
                                        <th scope="col">Jumlah Masuk</th>
                                        <th scope="col">Tanggal Masuk</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach ($historys as $history)
                                        <tr>
                                            <th scope="row">{{ $loop->iteration }}</th>
                                            <td>{{ $history->namaProduk }}</td>
                                            <td>{{ $history->kemasan }}</td>
                                            <td>{{ $history->jumlahMasuk." ".$history->satuan }}</td>
                                            <td>{{ $history->tanggal }}</td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Widgets End -->


            <!-- Footer Start -->
            <div class="container-fluid pt-4 px-4">
                <div class="bg-secondary rounded-top p-4">
                    <div class="row">
                        <div class="col-12 col-sm-6 text-center text-sm-start">
                            &copy; <a href="#">Your Site Name</a>, All Right Reserved.
                        </div>
                        <div class="col-12 col-sm-6 text-center text-sm-end">
                            <!--/*** This template is free as long as you keep the footer author’s credit link/attribution link/backlink. If you'd like to use the template without the footer author’s credit link/attribution link/backlink, you can purchase the Credit Removal License from "https://htmlcodex.com/credit-removal". Thank you for your support. ***/-->
                            Designed By <a href="https://htmlcodex.com">HTML Codex</a>
                            <br>Distributed By: <a href="https://themewagon.com" target="_blank">ThemeWagon</a>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Footer End -->
        </div>
        <!-- Content End -->


        <!-- Back to Top -->
        <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>
    </div>
@endsection